name: ct-train-and-upload

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train_and_promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Make sure Python is present and consistent
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 2) Auth to GCP using your repo secret key
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      # 3) Sanity: show the files we checked out
      - name: Show repo tree
        run: ls -R

      # 4) Install deps (this MUST include joblib, scikit-learn, etc.)
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r training/requirements.txt

      # 5) Train & maybe promote
      - name: Train and maybe promote
        env:
          PROJECT_ID:   ${{ secrets.PROJECT_ID }}
          BQ_TABLE:     ${{ secrets.BQ_TABLE }}
          MODEL_BUCKET: ${{ secrets.MODEL_BUCKET }}
        run: python training/train.py

      # 6) Debug output + artifact check
      - name: Show promotion result
        run: cat promotion.json || true

      - name: Verify artifacts in GCS
        run: |
          gsutil ls gs://${{ secrets.MODEL_BUCKET }}/registry/current/ || true
          gsutil ls gs://${{ secrets.MODEL_BUCKET }}/registry/versions/ || true
