name: ct-train-and-upload

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train_and_promote:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          echo "==== repo tree ===="
          ls -R
          echo "==== show requirements.txt ===="
          test -f training/requirements.txt && cat training/requirements.txt || (echo "training/requirements.txt NOT FOUND"; exit 1)
          echo "==== installing ===="
          python -m pip install -r training/requirements.txt
          echo "==== import smoke test ===="
          python -c "import joblib, sklearn, pandas, numpy; from google.cloud import bigquery, storage; print('All deps import ok')"

      - name: Train and maybe promote
        env:
          PROJECT_ID:   ${{ secrets.PROJECT_ID }}
          BQ_TABLE:     ${{ secrets.BQ_TABLE }}
          MODEL_BUCKET: ${{ secrets.MODEL_BUCKET }}
        run: python training/train.py

      - name: Show promotion result
        run: cat promotion.json || true

      - name: Verify artifacts in GCS
        run: |
          gsutil ls gs://${{ secrets.MODEL_BUCKET }}/registry/current/ || true
          gsutil ls gs://${{ secrets.MODEL_BUCKET }}/registry/versions/ || true
